version: "3.7"

services:

  invest_gui:
    image: invest_gui:latest
    container_name: invest_gui
    ports:
      - 8000:80
    depends_on:
      - invest_api
    networks:
      - invest_api_network

  invest_api:
    build: ..
    image: invest_api:latest
    container_name: invest_api
    ports:
      - 8080:8080
    environment:
      - DB_URL=postgresql://postgres:ch1buc.0_o@40.118.82.131:5432/invest_db
    depends_on:
      - invest_migrations
    networks:
      - invest_api_network

  invest_migrations:
    image: invest_api:latest
    container_name: invest_migrations
    environment:
      - DB_URL=postgresql://${DB_USER}:${DB_PASSWORD}@invest_db:5432/${DB_PASSWORD}
    command: sh -c "sleep 2 && alembic upgrade head"
    depends_on:
      - invest_db
    networks:
      - invest_api_network

  invest_db:
    image: postgres:11-alpine
    container_name: invest_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - invest_api_network

networks:
  invest_api_network:
    name: invest_api_network
